/*++

Copyright (C) 1994-1996 Microsoft Corporation

Module Name:

    RnrMsg.h

Abstract:

    This file is generated by the MC tool from the RNRMSG.MC message
    file.

Author:

    Charles K. Moore (keithmo)   24-July-1994

Revision History:

--*/

#ifndef _RNRMSG_H_
#define _RNRMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: RNR_EVENT_SYSTEM_CALL_FAILED
//
// MessageText:
//
//  A call to a system service failed unexpectedly.  The data is the error.
//
#define RNR_EVENT_SYSTEM_CALL_FAILED     0xC0000001L

//
// MessageId: RNR_EVENT_CANNOT_INITIALIZE_WINSOCK
//
// MessageText:
//
//  Cannot initialize the Windows Sockets library.  The data is the error.
//
#define RNR_EVENT_CANNOT_INITIALIZE_WINSOCK 0xC0000002L

//
// MessageId: RNR_EVENT_CANNOT_GET_GUID
//
// MessageText:
//
//  Cannot determine the GUID for this service.  The data is the error.
//
#define RNR_EVENT_CANNOT_GET_GUID        0xC0000003L

//
// MessageId: RNR_EVENT_CANNOT_OPEN_LISTENING_SOCKETS
//
// MessageText:
//
//  Cannot open the listening sockets to accept connections.  The data is the error.
//
#define RNR_EVENT_CANNOT_OPEN_LISTENING_SOCKETS 0xC0000004L

//
// MessageId: RNR_EVENT_CANNOT_ADVERTISE_SERVICE
//
// MessageText:
//
//  Cannot advertise the service.  The data is the error.
//
#define RNR_EVENT_CANNOT_ADVERTISE_SERVICE 0xC0000005L

//
// MessageId: RNR_EVENT_CANNOT_CREATE_LISTEN_THREAD
//
// MessageText:
//
//  Cannot create the listening thread.  The data is the error.
//
#define RNR_EVENT_CANNOT_CREATE_LISTEN_THREAD 0xC0000006L

//
// MessageId: RNR_EVENT_SELECT_FAILURE
//
// MessageText:
//
//  The select() API failed unexpectedly.  The data is the error.
//
#define RNR_EVENT_SELECT_FAILURE         0xC0000007L

//
// MessageId: RNR_EVENT_ACCEPT_FAILURE
//
// MessageText:
//
//  The accept() API failed unexpectedly.  The data is the error.
//
#define RNR_EVENT_ACCEPT_FAILURE         0xC0000008L

//
// MessageId: RNR_EVENT_RECEIVE_FAILURE
//
// MessageText:
//
//  The send() API failed unexpectedly.  The data is the error.
//
#define RNR_EVENT_RECEIVE_FAILURE        0xC0000009L

//
// MessageId: RNR_EVENT_SEND_FAILURE
//
// MessageText:
//
//  The recv() API failed unexpectedly.  The data is the error.
//
#define RNR_EVENT_SEND_FAILURE           0xC000000AL

//
// MessageId: RNR_EVENT_CREATE_EVENT_FAILURE
//
// MessageText:
//
//  Cannot create client thread event.  The data is the error.
//
#define RNR_EVENT_CREATE_EVENT_FAILURE   0xC000000BL

//
// MessageId: RNR_EVENT_CANNOT_CREATE_CLIENT
//
// MessageText:
//
//  Cannot create client context data.  The data is the error.
//
#define RNR_EVENT_CANNOT_CREATE_CLIENT   0xC000000CL

//
// MessageId: RNR_EVENT_CANNOT_CREATE_WORKER_THREAD
//
// MessageText:
//
//  Cannot create client worker thread.  The data is the error.
//
#define RNR_EVENT_CANNOT_CREATE_WORKER_THREAD 0xC000000DL

//
// MessageId: RNR_EVENT_TOO_MANY_CLIENTS
//
// MessageText:
//
//  Too many connected clients.
//
#define RNR_EVENT_TOO_MANY_CLIENTS       0xC000000EL


#endif  // _RNRMSG_H_

